window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t390_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var escapeEvent=t390_escClosePopup.bind(this,recId);if(popupTooltipHook){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});document.addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t390_showPopup(recId,escapeEvent);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t390__lazyLoad();if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,popupTooltipHook)})}
popup.addEventListener('scroll',t_throttle(function(){t390__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t390_closePopup(recId,escapeEvent)});popupCloseBtn.addEventListener('click',function(){t390_closePopup(recId,escapeEvent)});for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup(recId,escapeEvent);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t-body_popupshowed')},300)}}})}
var curPath=window.location.pathname;var curFullPath=window.location.origin+curPath;var isAndroid=/(android)/i.test(navigator.userAgent);if(isAndroid){var selects='a[href^="#"]:not([href="#"]):not([href^="#price"]):not([href^="#popup"]):not([href^="#prodpopup"]):not([href^="#order"]):not([href^="#!"]),'+'a[href^="'+curPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"]),'+'a[href^="'+curFullPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"])';var selectors=rec.querySelectorAll(selects);for(var i=0;i<selectors.length;i++){selectors[i].addEventListener('click',function(event){var hash=this.hash.trim();if(window.location.hash){setTimeout(function(){window.location.href=hash},50)}})}}
function t390_escClosePopup(recId){if(arguments[1].key==='Escape')t390_closePopup(recId,escapeEvent)}}
function t390_showPopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return;if(screenMax&&windowWidth>parseInt(screenMax,10))return;var popup=rec.querySelector('.t-popup');var documentBody=document.body;t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t390__body_popupshowed');document.addEventListener('keydown',escapeEvent)}
function t390_closePopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupActive=document.querySelector('.t-popup.t-popup_show');if(popup===popupActive){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t390__body_popupshowed')}
popup.classList.remove('t-popup_show');t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',escapeEvent)}
function t390_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390__lazyLoad(){var allRecords=document.getElementById('allrecords');if(window.lazy==='y'||(allRecords&&allRecords.getAttribute('data-tilda-lazy')==='yes')){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t1014_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t1014');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var hrefs=rec.querySelectorAll('a[href*="#"]');var popup=rec.querySelector('.t-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');if(popupTooltipHook){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});document.addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t1014_createPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t1014__lazyLoad();if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,popupTooltipHook)})}
popup.addEventListener('scroll',t_throttle(function(){t1014__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t1014_closePopup()});popupCloseBtn.addEventListener('click',t1014_closePopup);for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||(url.substring(0,7)!='#price:'&&url.substring(0,7)!='#order:')){t1014_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed')},300)}}})}}
function t1014_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=typeof window.pageYOffset!=='undefined'?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t1014_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t1014_createPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t1014');if(!container)return;var popup=rec.querySelector('.t-popup');var documentBody=document.body;t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t1014__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t1014_lockScroll()},500)}
document.addEventListener('keydown',t1014_escClosePopup)}
function t1014_escClosePopup(event){if(event.key==='Escape')t1014_closePopup()}
function t1014_closePopup(){var popupAll=document.querySelectorAll('.t-popup');if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t1014__body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t1014_unlockScroll()}
t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t1014_escClosePopup)}
function t1014__lazyLoad(){var allRecords=document.getElementById('allrecords');if(window.lazy==='y'||(allRecords&&allRecords.getAttribute('data-tilda-lazy')==='yes')){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t1014_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t939_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t886_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var notificationBlock=rec.querySelector('.t886');var closeButton=rec.querySelector('.t886__btn');var storageItem=notificationBlock.getAttribute('data-storage-item');var lastOpen;try{lastOpen=localStorage.getItem(storageItem)}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}
if(!lastOpen){notificationBlock.classList.remove('t886_closed')}
if(closeButton){closeButton.addEventListener('click',function(event){notificationBlock.classList.add('t886_closed');try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}
event.preventDefault()})}}
window.requestAnimationFrame=(function(){return(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60)})})();function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);var excludeHashes=['#!/tproduct/','#!/tab/','#opencart'];if(excludeHashes.includes(hash)){return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;t270_scrollToEl(hash,offset);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(hash,offset){var SCROLL_DURATION_MS=500;var body=document.body;if(body.getAttribute('data-scroll'))return;var scrollTargetY=t270_getTarget(hash,offset);if(isNaN(scrollTargetY))return;var canSmoothScroll=window.CSS&&window.CSS.supports('scroll-behavior','smooth')&&'scrollBehavior' in document.documentElement.style;var userAgent=navigator.userAgent.toLowerCase();var isAndroid=userAgent.indexOf('android')!==-1;if(window.isMobile&&!isAndroid&&canSmoothScroll){body.setAttribute('data-scroll','true');window.scrollTo({left:0,top:scrollTargetY,behavior:'smooth',});setTimeout(function(){body.removeAttribute('data-scroll')},SCROLL_DURATION_MS)}else{t270_smoothScrollTo(scrollTargetY,SCROLL_DURATION_MS)}}
function t270_smoothScrollTo(targetY,duration=500){var body=document.body;var startY=window.scrollY||window.pageYOffset;var deltaY=targetY-startY;var startTime=performance.now();function easeInOutQuad(t){return Math.pow(t,2)}
function scroll(){var currentTime=performance.now();var elapsedTime=Math.min((currentTime-startTime)/duration,1);var ease=easeInOutQuad(elapsedTime);window.scrollTo(0,startY+deltaY*ease);if(elapsedTime<1){requestAnimationFrame(scroll)}else{body.removeAttribute('data-scroll');body.removeAttribute('data-scrollable');window.scrollTo(0,targetY)}}
body.setAttribute('data-scroll','true');body.setAttribute('data-scrollable','true');requestAnimationFrame(scroll)}
function t270_getTarget(hash,offset){var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"], div[id="'+hash.substr(1)+'"]');if(!target)return}
target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);target=Math.max(target,0);return target}
function t875_init(){if(document.layers){document.captureEvents(Event.MOUSEDOWN)}
document.onmousedown=t875_click;document.oncontextmenu=function(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}else{return!1}};t875_preventSelection(document);t875_preventUserSelect()}
function t875_preventUserSelect(){var oldStyle=document.body.getAttribute('style');document.body.style.cssText=oldStyle+'-ms-user-select: none;'+'-moz-user-select: none;'+'-webkit-user-select: none;'+'user-select: none;'+'-webkit-touch-callout: none;'}
function t875_click(event){t875_returnPrevent(event);if(document.all){if(event.button===2){return!1}}
if(document.layers){if(event.which===3){return!1}}}
function t875_preventSelection(element){var preventSelection=!1;t875_addHandler(element,'mousemove',function(){if(preventSelection){t875_removeSelection()}});t875_addHandler(element,'mousedown',function(event){event=event||window.event;var sender=event.target||event.srcElement;preventSelection=sender&&!sender.tagName.match(/INPUT|TEXTAREA/i)&&!sender.hasAttribute('contenteditable')&&sender.parentElement&&!sender.parentElement.hasAttribute('contenteditable')});t875_addHandler(element,'mouseup',function(){if(preventSelection){t875_removeSelection()}
preventSelection=!1});t875_addHandler(element,'keydown',t875_killCtrlA);t875_addHandler(element,'keyup',t875_killCtrlA);t875_addHandler(element,'keydown',t875_killCtrlU);t875_addHandler(element,'keyup',t875_killCtrlU);t875_addHandler(element,'keydown',t875_killAltCmdI);t875_addHandler(element,'keyup',t875_killAltCmdI);t875_addHandler(element,'keydown',t875_killCtrlShiftI);t875_addHandler(element,'keyup',t875_killCtrlShiftI)}
function t875_addHandler(element,event,handler){if(element.attachEvent){element.attachEvent('on'+event,handler)}else if(element.addEventListener){element.addEventListener(event,handler,!1)}}
function t875_removeSelection(){if(window.getSelection){window.getSelection().removeAllRanges()}else if(document.selection&&document.selection.clear){document.selection.clear()}}
function t875_killCtrlU(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if((event.ctrlKey&&key=='U'.charCodeAt(0))||(event.altKey&&event.metaKey&&(key=='U'.charCodeAt(0)||key=='u'.charCodeAt(0)))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killAltCmdI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.altKey&&event.metaKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlShiftI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.shiftKey&&event.ctrlKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlA(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA|BUTTON/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}
var key=event.keyCode||event.which;if((event.ctrlKey&&key=='A'.charCodeAt(0))||(event.metaKey&&key=='A'.charCodeAt(0))){t875_removeSelection();if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_returnPrevent(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}}
function t966_init(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t966'):null;var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(!hook)return;var hookLinks=document.querySelectorAll('a[href="'+hook+'"]');hookLinks=Array.prototype.filter.call(hookLinks,function(hookLink){var isSubmenuAllowed=hookLink.getAttribute('data-submenu-disallowed')!=='yes';if(isSubmenuAllowed){hookLink.classList.add('t966__tm-link');hookLink.setAttribute('data-tooltip-menu-id',recid);return!0}
return!1});var parentMenu=hookLinks.length?hookLinks[0].closest('[data-menu]'):null;var tooltipMenu=rec.querySelector('.t966__tooltip-menu');var isParentFixed=parentMenu&&window.getComputedStyle(parentMenu).position==='fixed';if(tooltipMenu)tooltipMenu.setAttribute('data-pos-fixed',isParentFixed?'yes':'no');t966_addArrow(recid,hookLinks);t966_setUpMenu(recid,hookLinks);t_onFuncLoad('t_submenublocks__highlightActiveLinks',function(){t_submenublocks__highlightActiveLinks('.t966__menu-link')});var isT804Exist=!!document.querySelector('.t804');if(isT804Exist&&!rec.hasAttribute('data-t966-geo-bound')){rec.setAttribute('data-t966-geo-bound','true');document.addEventListener('replacingCompleted',function(){t966_init(recid)})}
if(menu.hasAttribute('data-full-submenu-mob')&&(window.isMobile||'ontouchend' in document)){t_onFuncLoad('t_submenublocks__setFullScreenMenu',function(){t_submenublocks__setFullScreenMenu(menu)})}}
function t966_divideMenu(recid,rows){var rec=document.getElementById('rec'+recid);if(!rec)return;if(!rows)rows=1;var menu=rec.querySelector('.t966');if(menu&&menu.getAttribute('data-sort-mobile')==='yes'&&window.innerWidth<980)return;var items=rec.querySelectorAll('.t966__menu-item-wrapper');var list=rec.querySelector('.t966__menu-list');var maxItemsCountInRow=Math.ceil(items.length/rows);var rowClass='t966__menu-list-row_'+(100/rows).toFixed();for(var i=0;i<maxItemsCountInRow;i++){var row=document.createElement('div');row.classList.add('t966__menu-list-row');row.classList.add(rowClass);if(list)list.appendChild(row)}
var listRows=list?list.querySelectorAll('.t966__menu-list-row'):[];Array.prototype.forEach.call(items,function(item,i){if(listRows[i%maxItemsCountInRow])listRows[i%maxItemsCountInRow].appendChild(item)});var allRec=document.getElementById('allrecords');var currentMode=allRec?allRec.getAttribute('data-tilda-mode'):'';if(currentMode==='edit'){var tooltipItems=document.querySelectorAll('.t966__tooltip-menu');Array.prototype.forEach.call(tooltipItems,function(item){item.style.display='block'})}}
function t966_addArrow(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenuBlock=rec?rec.querySelector('.t966'):null;var isArrowAppend=submenuBlock.getAttribute('data-add-arrow');if(!isArrowAppend)return;hookLinks=Array.prototype.slice.call(hookLinks);hookLinks.forEach(function(hookLink){if(hookLink.querySelector('.t966__arrow'))return;var arrow=document.createElement('div');arrow.classList.add('t966__arrow');hookLink.appendChild(arrow);var isInsideZero=hookLink.closest('.tn-atom');var hasCustomBorderColor=window.getComputedStyle(hookLink).borderColor!=='rgba(0, 0, 0, 0)';if(isInsideZero&&!hasCustomBorderColor){hookLink.style.borderColor='initial';hookLink.style.border='none'}})}
function t966_setUpMenu(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenu=rec?rec.querySelector('.t966__tooltip-menu'):null;if(!submenu)return;var content=submenu.querySelector('.t966__content');var menu=rec.querySelector('.t966');var verticalIndent=menu?menu.getAttribute('data-tooltip-margin'):'';var hooksAndSubmenu=hookLinks.concat(submenu);var timer;if(window.innerWidth>980&&!('ontouchend' in document)){t_onFuncLoad('t_submenublocks__addEventsDesktop',function(){t_submenublocks__addEventsDesktop(submenu,hooksAndSubmenu,verticalIndent,'.t966')})}else{t_onFuncLoad('t_submenublocks__addEventsMobile',function(){t_submenublocks__addEventsMobile(submenu,hookLinks,verticalIndent,'.t966')})}
document.addEventListener('click',function(e){if(submenu.getAttribute('data-mobiletooltip')!=='yes')return;if(!e.target.closest('.t966__tooltip-menu')&&!e.target.classList.contains('t966__tm-link')&&!e.target.closest('.t966__tm-link')){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t966')})}});window.addEventListener('scroll',t_throttle(function(){if(content){content.addEventListener('mouseleave',function(){var activeEl=hookLinks.filter(function(el){return el.classList.contains('t966__tm-link_active')});var afterActiveEl=activeEl.length?activeEl[0].nextElementSibling:null;if(submenu.classList.contains('t966__tooltip-menu_show')||(afterActiveEl&&afterActiveEl.classList.contains('t966__tooltip-menu_mobile'))){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(afterActiveEl,'.t966')})}})}},300));window.addEventListener('resize',t_throttle(function(){if(window.isMobile||window.innerWidth<980)return;var mobileMenu=document.querySelector('.t966__tooltip-menu_mobile');t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(mobileMenu,'.t966')})},300));var submenuLinks=submenu.querySelectorAll('a[href*="#"]');Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t966',link)});var clickedInTooltipMenuEls=document.querySelectorAll('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466');Array.prototype.forEach.call(clickedInTooltipMenuEls,function(el){var event=document.createEvent('Event');event.initEvent('clickedAnchorInTooltipMenu',!0,!0);el.dispatchEvent(event)});Array.prototype.forEach.call(submenuLinks,function(otherLink){var linkTitle=otherLink.querySelector('.t966__menu-item-title');if(otherLink!==link){if(linkTitle)linkTitle.classList.remove('t-active')}else{if(linkTitle)linkTitle.classList.add('t-active')}})})})}
function t389_scrollToTop(){var duration=700;var difference=window.pageYOffset;var step=(10*difference)/duration;var timer=setInterval(function(){difference-=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(window.pageYOffset===0){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10)}