window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t383_highlight(link){if(link){var links=document.querySelectorAll('a[href="'+link+'"]');Array.prototype.forEach.call(links,function(link){link.classList.add('t-active');link.setAttribute('data-highlighted-by-user','y')})}}
function t282_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t282');var submenu=rec.querySelector('.t-menusub__container');var allRec=document.getElementById('allrecords');var isEdit=allRec?allRec.getAttribute('data-tilda-mode')==='edit':!1;if(isEdit&&submenu){submenu.style.position='relative';submenu.style.zIndex='10';submenu.style.pointerEvents='none'}
var menuLinks=rec.querySelectorAll('.t-menusub__link-item');var menuContainer=rec.querySelector('.t282__container');var menuAndOverlay=rec.querySelectorAll('.t282__container, .t282__menu__container, .t282__overlay');var canBeClickedItems=rec.querySelectorAll('.t282 .t-menuburger, .t282__menu__link:not(.tooltipstered):not(.t282__menu__link_submenu), .t282__overlay');var menuBlock=rec.querySelector('.t282__menu__container');var menuWrapper=menu.querySelector('.t282__menu__wrapper');var menuContainerHeight=menuContainer?menuContainer.getBoundingClientRect().height:0;var menuBurger=menu?menu.querySelector('.t-menuburger'):null;Array.prototype.forEach.call(canBeClickedItems,function(element){element.addEventListener('click',function(){if((element.classList.contains('t282__overlay')&&element.classList.contains('t282__closed'))||element.closest('.t282__menu__link.tooltipstered, .t794__tm-link, .t978__tm-link, .t966__tm-link'))return;if(document.body.classList.contains('t282_opened')){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t282_opened')}else{if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t282_opened')}
Array.prototype.forEach.call(menuAndOverlay,function(el){el.style.transform='';if(element.closest('.t-menuburger')&&el.closest('.t282__menu__container')&&el.classList.contains('t282__closed')&&!window.isMobile){el.style.pointerEvents='none';setTimeout(function(){el.style.pointerEvents=''},500)}
var menuContainerHeight=menuContainer?menuContainer.getBoundingClientRect().height:0;if(element.closest('.t-menuburger')&&menuWrapper.clientHeight>menuBlock.clientHeight&&!el.classList.contains('t282__closed')&&!el.classList.contains('t282__container')){el.style.transform='translateY(calc(-100% - '+menuContainerHeight+'px))'}
el.classList.toggle('t282__closed')});if(menuBlock)menuBlock.style.top=menuContainerHeight+'px';var menuBurger=rec.querySelector('.t-menuburger')
if(menuBurger)menuBurger.classList.toggle('t-menuburger-opened',document.body.classList.contains('t282_opened'))
if(element.classList.contains('t-menuburger')){var expandedStatus=element.classList.contains('t-menuburger-opened');element.setAttribute('aria-expanded',expandedStatus)}
t282_highlight(recid)})});menu.addEventListener('clickedAnchorInTooltipMenu',function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t282_opened');Array.prototype.forEach.call(menuAndOverlay,function(el){el.classList.add('t282__closed')})});Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t282_opened');Array.prototype.forEach.call(menuAndOverlay,function(el){el.classList.add('t282__closed');if(menuBurger){menuBurger.classList.remove('t-menuburger-opened');menuBurger.setAttribute('aria-expanded',!1)}})})})}
function t282_changeSize(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t282__container');var menuContainer=rec.querySelector('.t282__menu__container');var menuWrapper=document.getElementById('nav'+recid);var menuHeight=menu?menu.offsetHeight:0;var menuContainerHeight=menuContainer?menuContainer.offsetHeight:0;if(menuHeight>document.documentElement.clientHeight-menuContainerHeight){if(menuWrapper)menuWrapper.classList.add('t282__menu_static')}else{if(menuWrapper)menuWrapper.classList.remove('t282__menu_static')}}
function t282_changeBgOpacityMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t282__container__bg');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity2');var menuShadowOpacity=parseInt(menu.getAttribute('data-menushadow'),10)||0;menuShadowOpacity/=100;var menuShadowCSS=menu.getAttribute('data-menushadow-css');menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if((window.pageYOffset>20&&bgOpacityTwo==='0')||(window.pageYOffset<=20&&(bgOpacity==='0.0'||bgOpacity==='0'))||(!menuShadowOpacity&&!menuShadowCSS)){menu.style.boxShadow='none'}else if(menuShadowCSS){menu.style.boxShadow=menuShadowCSS}else if(menuShadowOpacity){menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowOpacity+')'}})}
function t282_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t282__menu a[href=\''+url+'\'], '+'.t282__menu a[href=\''+url+'/\'], '+'.t282__menu a[href=\''+pathname+'\'], '+'.t282__menu a[href=\'/'+pathname+'\'], '+'.t282__menu a[href=\''+pathname+'/\'], '+'.t282__menu a[href=\'/'+pathname+'/\']'+(hash?', .t282__menu a[href=\''+hash+'\']':'')+(hash?', .t282__menu a[href=\'/'+hash+'\']':'')+(hash?', .t282__menu a[href=\''+hash+'/\']':'')+(hash?', .t282__menu a[href=\'/'+hash+'/\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t282__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t282_appearMenu(recid){var record=document.getElementById('rec'+recid);var menuBlock=record.querySelector('.t282');var fixedMenu=menuBlock?menuBlock.querySelector('.t282__positionfixed'):null;if(!fixedMenu)return;var appearOffset=menuBlock.getAttribute('data-appearoffset');if(appearOffset&&appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=fixedMenu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(fixedMenu.style.transform==='translateY(-'+menuHeight+'px)'){t282_slideUpElement(fixedMenu,menuHeight,'toBottom')}}else if(fixedMenu.style.transform==='translateY(0px)'){t282_slideUpElement(fixedMenu,menuHeight,'toTop')}else{fixedMenu.style.transform='translateY(-'+menuHeight+'px)';fixedMenu.style.opacity='0'}}
function t282_slideUpElement(menu,menuHeight,direction){var diff=direction==='toTop'?0:menuHeight;var diffOpacity=direction==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=direction==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=direction==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(direction==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(direction==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t794_init(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t794'):null;var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(!hook)return;var hookLinks=document.querySelectorAll('a[href="'+hook+'"]');hookLinks=Array.prototype.filter.call(hookLinks,function(hookLink){var isSubmenuAllowed=hookLink.getAttribute('data-submenu-disallowed')!=='yes';if(isSubmenuAllowed){hookLink.classList.add('t794__tm-link');hookLink.setAttribute('data-tooltip-menu-id',recid);return!0}
return!1});var parentMenu=hookLinks.length?hookLinks[0].closest('[data-menu]'):null;var tooltipMenu=rec.querySelector('.t794__tooltip-menu');var isParentFixed=parentMenu&&window.getComputedStyle(parentMenu).position==='fixed';if(tooltipMenu)tooltipMenu.setAttribute('data-pos-fixed',isParentFixed?'yes':'no');t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t_onFuncLoad('t_submenublocks__highlightActiveLinks',function(){t_submenublocks__highlightActiveLinks('.t794__list_item a')});if(menu.hasAttribute('data-full-submenu-mob')&&(window.isMobile||'ontouchend' in document)){t_onFuncLoad('t_submenublocks__setFullScreenMenu',function(){t_submenublocks__setFullScreenMenu(menu)})}}
function t794_addArrow(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenuBlock=rec?rec.querySelector('.t794'):null;var isArrowAppend=submenuBlock.getAttribute('data-add-arrow');if(!isArrowAppend)return;hookLinks=Array.prototype.slice.call(hookLinks);hookLinks.forEach(function(hookLink){var arrow=document.createElement('div');arrow.classList.add('t794__arrow');hookLink.appendChild(arrow);var isInsideZero=hookLink.closest('.tn-atom');var hasCustomBorderColor=window.getComputedStyle(hookLink).borderColor!=='rgba(0, 0, 0, 0)';if(isInsideZero&&!hasCustomBorderColor){hookLink.style.borderColor='initial';hookLink.style.border='none'}})}
function t794_setUpMenu(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenu=rec?rec.querySelector('.t794__tooltip-menu'):null;if(!submenu)return;var menuBlock=rec?rec.querySelector('.t794'):null;var verticalIndent=menuBlock.getAttribute('data-tooltip-margin');var content=submenu.querySelector('.t794__content');var hooksAndSubmenu=hookLinks.concat(submenu);if(window.innerWidth>980&&!('ontouchend' in document)){t_onFuncLoad('t_submenublocks__addEventsDesktop',function(){t_submenublocks__addEventsDesktop(submenu,hooksAndSubmenu,verticalIndent,'.t794')})}else{t_onFuncLoad('t_submenublocks__addEventsMobile',function(){t_submenublocks__addEventsMobile(submenu,hookLinks,verticalIndent,'.t794')})}
window.addEventListener('scroll',t_throttle(function(){if(content){content.addEventListener('mouseleave',function(){if(submenu.classList.contains('t794__tooltip-menu_show')){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t794')})}})}},300));var tooltipLinks=document.querySelectorAll('.t794__tooltip-menu a[href*="#"]');Array.prototype.forEach.call(tooltipLinks,function(tooltipLink){tooltipLink.addEventListener('click',function(){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t794')});var menuList=document.querySelectorAll('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466');Array.prototype.forEach.call(menuList,function(menu){var event=document.createEvent('Event');event.initEvent('clickedAnchorInTooltipMenu',!0,!0);menu.dispatchEvent(event)});Array.prototype.forEach.call(tooltipLinks,function(link){link.classList.remove('t-active')});tooltipLink.classList.add('t-active')})})}
function t410_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var wrapper=rec?rec.querySelector('.t410__wrapper'):null;if(!wrapper)return!1;var sliderOrientation=wrapper.getAttribute('data-beforeafter-orientation');var sliderStartPosition=wrapper.getAttribute('data-beforeafter-start');var firstImgURL=wrapper.getAttribute('data-beforeafter-imgurl-first');var firstImgDescr=wrapper.getAttribute('data-beforeafter-imgdescr-first');var firstImgAlt=wrapper.getAttribute('data-beforeafter-imgalt-first');var secondImgURL=wrapper.getAttribute('data-beforeafter-imgurl-second');var secondImgDescr=wrapper.getAttribute('data-beforeafter-imgdescr-second');var secondImgAlt=wrapper.getAttribute('data-beforeafter-imgalt-second');t410_onObjLoad('beforeafter',function(){new beforeafter.BASlider('#t410-beforeafter__'+recid,[{src:firstImgURL,label:firstImgDescr,alt:firstImgAlt,},{src:secondImgURL,label:secondImgDescr,alt:secondImgAlt,},],{mode:sliderOrientation?sliderOrientation:'horizontal',startingPosition:sliderStartPosition?sliderStartPosition+'%':'50%',})});var block=rec.querySelector('.t410');if(typeof jQuery!=='undefined'){$(block).on('displayChanged',function(){window.beforeafter.sliders.forEach(function(obj){if(obj.options.wrapper.getAttribute('id')==='t410-beforeafter__'+recid){obj.options.setWrapperDimensions()}})})}else if(block){block.addEventListener('displayChanged',function(){window.beforeafter.sliders.forEach(function(obj){if(obj.options.wrapper.getAttribute('id')==='t410-beforeafter__'+recid){obj.options.setWrapperDimensions()}})})}}
function t410_onObjLoad(objName,okFunc,time){if(typeof window[objName]==='object'){okFunc()}else{var timerId=setTimeout(function checkFuncExist(){if(typeof window[objName]==='object'){okFunc();return}
timerId=setTimeout(checkFuncExist,time||100)})}}
function t886_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var notificationBlock=rec.querySelector('.t886');var closeButton=rec.querySelector('.t886__btn');var storageItem=notificationBlock.getAttribute('data-storage-item');var lastOpen;try{lastOpen=localStorage.getItem(storageItem)}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}
if(!lastOpen){notificationBlock.classList.remove('t886_closed')}
if(closeButton){closeButton.addEventListener('click',function(event){notificationBlock.classList.add('t886_closed');try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}
event.preventDefault()})}}